name: Trigger auto deployment for caraml-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/caraml-server-AutoDeployTrigger-00513e53-5715-4ca6-abcb-bbf6dc91c171.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CARAMLSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CARAMLSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CARAMLSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.com
          registryUsername: ${{ secrets.CARAMLSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CARAMLSERVER_REGISTRY_PASSWORD }}
          containerAppName: caraml-server
          resourceGroup: caraml
          imageToBuild: docker.com/vclerc/caraml-server:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


